[theme]

# Primary accent for interactive elements
primaryColor = '#2D93AD'

# Background color for the main content area
backgroundColor = '#1C1C1C'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#2D2D2D'

# Color used for almost all text
textColor = '#F1F1F1'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
